### ISSUE TITLE
[Feature request] Support username/password authentication

### ISSUE THREAD

**Issue by pexcn** [heiher/hev-socks5-server#1]
Is there a plan to add this feature?

**Comment by pexcn** [comment]
Seems not working in telegram proxy settings.
![1](https://user-images.githubusercontent.com/4590439/49261427-1d08b780-f47d-11e8-9c6c-6df414bd23eb.png)
![2](https://user-images.githubusercontent.com/4590439/49261428-1da14e00-f47d-11e8-86a2-93a0c7e0616f.png)

but when I set no auth, it works fine.

**Comment by heiher** [comment]
https://github.com/heiher/hev-socks5-server/releases/tag/1.5.1

**Comment by pexcn** [comment]
Thank you, fixed in v1.5.1.
