### ISSUE TITLE
希望能添加一个支持上游 SOCKS5 的功能？

### ISSUE THREAD

**Issue by pexcn** [heiher/hev-socks5-server#11]
配置示例：
```ini
[Upstream]
UpstreamAddress=127.0.0.1
UpstreamPort=1080
UpstreamUsername=user
UpstreamPassword=passwd
```
假如我上游放了一个 `ss-local`，绑定在了 `127.0.0.1:1080`, 希望可以把流量转发到上游的 `socks5://127.0.0.1:1080` 来处理

**Comment by heiher** [comment]
请问具体用途是什么？

**Comment by pexcn** [comment]
相当于是把不能添加认证的socks5程序加个验证，但是加到这个程序里好像就不符合KISS原则了，我也使用gost+ss-local代替了，感谢回复。😅
