### ISSUE TITLE
`Create socket failed!` 的问题

### ISSUE THREAD

**Issue by pexcn** [heiher/hev-socks5-server#13]
在一个很小众的 NAT VPS 上运行，只有 IPv4 地址，启动不成功，显示：
```
Create socket failed!
```
```bash
# 退出的错误状态码为 253
root@HK-NAT:~# echo $?
253
```

但是把这行 https://github.com/heiher/hev-socks5-server/blob/master/src/hev-socks5-server.c#L49 的 `AF_INET6` 改成 `AF_INET` 似乎就能启动了，但是不知道能不能用，未测试。

**Comment by heiher** [comment]
是的，上次增加IPv6双栈支持时，就不考虑支持那种IPv4 Only的系统了。

**Comment by pexcn** [comment]
但是我其它 VPS 也有只有 IPv4 的，但是为什么也能用？
此外我这个 VPS (openvz) 是从 Debian 8 升级到 Debian 9 的，跟这个有关吗？

**Comment by heiher** [comment]
> 但是我其它 VPS 也有只有 IPv4 的，但是为什么也能用？
如果内核是支持ipv6的，但只配置了ipv4地址，这种情况是支持的。不支持的是内核都没有ipv6支持。

> 此外我这个 VPS (openvz) 是从 Debian 8 升级到 Debian 9 的，跟这个有关吗？
主要是内核是否支持ipv6，可以用这个命令确认下（net.ipv6.conf.all.disable_ipv6 = 0）：
```
sysctl net.ipv6.conf.all.disable_ipv6
```

**Comment by pexcn** [comment]
我知道了，看来是内核不支持，sysctl -a | grep ipv6 没有任何相关的东西
