### ISSUE TITLE
Need more document for Android

### ISSUE THREAD

**Issue by songoten28** [heiher/hev-socks5-server#14]
When I compiled code successfully with ndk-build
I don't know what to do next with .so file?

Can you provider more details?

**Comment by heiher** [comment]
Please update to [1.9.4](https://github.com/heiher/hev-socks5-server/releases/tag/1.9.4), that will compile to an executable binary, and reference document [How to Use](https://github.com/heiher/hev-socks5-server#how-to-use).

**Comment by songoten28** [comment]
Thanks for really help.
