### ISSUE TITLE
Feature request: bind address support

### ISSUE THREAD

**Issue by nxtreaming** [heiher/hev-socks5-server#20]
Dear:

Please add bind feature to specify the IP which is used to select the out-going packet router if there are many ethernets

Thanks.

**Comment by heiher** [comment]
It's already supported by 'listen-address' in the config file.

For IPv4:
```yml
main:
  listen-address: ''::ffff:10.0.0.1'
```

For IPv4:
```yml
main:
  listen-address: ''2600:111:2222:3333::123'
```

**Comment by nxtreaming** [comment]
Thanks, but it doest not work, it just listen-address, not the client connect reply address.

# Main configuration for hev-socks5-server

main:
  # Worker threads
  workers: 2
  # Listen port
  port: 13884
  # Listen address (ipv4|ipv6)
  listen-address: '::ffff:23.228.65.98'

auth:
  username: "rack02"
  password: "rack02.20210829"

misc:
   # task stack size (bytes)
  task-stack-size: 262144
   # connect timeout (ms)
  connect-timeout: 5000
   # read-write timeout (ms)
  read-write-timeout: 60000
   # stdout, stderr or file-path
  log-file: stderr
   # debug, info, warn or error
  log-level: warn
   # If present, run as a daemon with this pid file
  pid-file: /run/hev-socks5-server-rack02-01.pid
   # If present, set rlimit nofile; else use default value
  limit-nofile: 2048
~                                                                       

------------------------
curl --socks5 rack02:rack02.20210829@23.228.65.98:13884 https://ifconfig.me

I will not get the ip: 23.228.65.98, but my main ethernet IP such as 104.148.x.y

please check the following project for explictly bind-address usage by "-b bindaddress " options

https://github.com/rofl0r/microsocks

microsocks -1 -i listenip -p port -u user -P password -b bindaddr

**Comment by heiher** [comment]
Hm, OK. Bind is used to select a source address to access the upstream server.

**Comment by nxtreaming** [comment]
> Hm, OK. Bind is used to select a source address to access the upstream server.

YES, this feature is missing.

the default mode should we the listen address to access upstream server.

**Comment by nxtreaming** [comment]
Thanks you.
