### ISSUE TITLE
编译错误，缺失yaml.h

### ISSUE THREAD

**Issue by ukhack** [heiher/hev-socks5-server#28]
root@VM-0-18-ubuntu:/# cd hev-socks5-server-2.4.6/
root@VM-0-18-ubuntu:/hev-socks5-server-2.4.6# make
src/hev-config.c:13:10: fatal error: yaml.h: No such file or directory
   13 | #include <yaml.h>
      |          ^~~~~~~~
compilation terminated.
make: *** [Makefile:101: build/hev-config.o] Error 1

尝试docker build -t hev-socks5-server -f docker/Dockerfile .
同样错误
(17/21) Installing make (4.3-r1)
(18/21) Installing fortify-headers (1.1-r1)
(19/21) Installing patch (2.7.6-r8)
(20/21) Installing build-base (0.5-r3)
(21/21) Installing .build-deps (20221201.033942)
Executing busybox-1.35.0-r29.trigger
OK: 244 MiB in 36 packages
make: git: No such file or directory
make: git: No such file or directory
make: git: No such file or directory
src/hev-config.c:13:10: fatal error: yaml.h: No such file or directory
   13 | #include <yaml.h>
      |          ^~~~~~~~
compilation terminated.
src/hev-main.c:15:10: fatal error: hev-task.h: No such file or directory
   15 | #include <hev-task.h>
      |          ^~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:101: build/hev-config.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** [Makefile:101: build/hev-main.o] Error 1
The command '/bin/sh -c apk update   && apk add --no-cache --virtual .build-deps build-base   && cd /tmp/hev-socks5-server   && make -j$(nproc)   && make install INSTDIR="/app"   && make clean   && cd /   && rm -r /tmp/hev-socks5-server   && apk del .build-deps   && rm -rf /var/cache/apk/*' returned a non-zero code: 2

**Comment by ukhack** [comment]
version: Tag 2.4.6

**Comment by heiher** [comment]
Clone with `--recursive`:

```shell
git clone --recursive https://github.com/heiher/hev-socks5-server
```
