### ISSUE TITLE
用户名和密码不完全匹配也能通过验证

### ISSUE THREAD

**Issue by pexcn** [heiher/hev-socks5-server#3]
假设我的用户名/密码是这样的

```ini
;...
[Auth]
Username=hello
Password=123456
```

在 Telegram 里面测试，以下口令都能通过验证：
用户名：h
密码：123456

用户名：hello
密码：1

用户名：h
密码：1

这两个地方只要匹配到前面任意字符就能通过验证。

**Comment by heiher** [comment]
Thank you.
Fixed [1.5.3](https://github.com/heiher/hev-socks5-server/releases/tag/1.5.3)

**Comment by pexcn** [comment]
谢谢~
