### ISSUE TITLE
What's FWD UDP and how / why would I use it ?

### ISSUE THREAD

**Issue by LindaFerum** [heiher/hev-socks5-server#33]
The readme mentions nonstandard FWD UDP functionality, but not much is explained about it and I am curious, would very much be grateful for an explainer

**Comment by heiher** [comment]
The non-standard `FWD UDP` command is used for UDP relay in TCP.

Related source codes (keyword `UDP_IN_TCP`):
- https://github.com/heiher/hev-socks5-core/blob/master/src/hev-socks5-server.c
- https://github.com/heiher/hev-socks5-core/blob/master/src/hev-socks5-udp.c
