### ISSUE TITLE
Could you please explain connect-timeout and read-write timeout?

### ISSUE THREAD

**Issue by LindaFerum** [heiher/hev-socks5-server#35]
Could you please explain in more detail connect-timeout and read-write timeout ?

Specific context:
suppose I'm trying to proxy a TCP connection that's supposed to be long-lived and receive only rather occasional keepalives (like android GMS service's "heartbeat" which often beats like once 10 minutes or so) and don't expect to roam that much

Which value should I increase, if any?

**Comment by heiher** [comment]
connect-timeout: The maximum waiting time that from the beginning of connecting to the remote host to the successful establishment of the connection.

read-write-timrout: After the connection is established, the maximum idle time without transmission in both directions.

> Which value should I increase, if any?

read-write-timeout

**Comment by LindaFerum** [comment]
Thanks!
