### ISSUE TITLE
hev-socks5-server instead of socks5 plugin in frpc

### ISSUE THREAD

**Issue by bannyhm** [heiher/hev-socks5-server#36]
As far as I understand the socks5 plugin in FRP does not support UDP. Is it possible with these frps.ini settings:
[common]
bind_addr = 0.0.0.0
bind_port = 9300
bind_udp_port = 9301
kcp_bind_port = 9300
quic_bind_port = 9302
dashboard_addr = 0.0.0.0
dashboard_port = 9500
dashboard_user = user
dashboard_pwd = user
enable_prometheus = true
detailed_errors_to_client = true
authentication_method = token
authenticate_heartbeats = false
authenticate_new_work_conns = false
token = 12345678
oidc_issuer =
oidc_audience =
oidc_skip_expiry_check = false
oidc_skip_issuer_check = false
allow_ports = 2000-7000,7001,7003,8000-60000
max_pool_count = 5
max_ports_per_client = 0
tls_only=false
subdomain_host=frps.com
tcp_mux=true
udp_packet_size = 1500
vhost_http_port = 80
vhost_https_port = 443
tcp_mux=true

and frpc.ini settings:

[common]
forward_all = tcp+udp
all_use_encryption = false
all_use_compression = false
server_addr = 188.xxx.xxx.54
server_port = 9300
plugin_user = user
plugin_passwd = user
authentication_method = token
token = 11111111
dns_server = 10.10.xxx.xxx

udp_forward=true

[web_udp992]
type=udp
local_ip = 127.0.0.1
local_port = 6350
remote_port = 6350
use_encryption=true
use_compression = false
protocol=udp

[plugin_socks5_992]
type=tcp
local_ip = 127.0.0.1
remote_port = 6350
plugin=socks5
plugin_user = user
plugin_passwd = user

If frpc is running on Android, Replace the built-in plugin with your Socks5 Server solution to get UDP support?

You answered me in another thread about setting up the schema without using frpc, but in that case my remote user is using Windows and is simultaneously connected to several socks5 servers.

**Comment by heiher** [comment]
Why don't you use frp port forwarding?

**Comment by bannyhm** [comment]
I'm very bad at this, as you can see from my questions.
The frpc client has a dynamic ip address and it changes every 10 minutes. Solutions using duckdns do not help, as I understand it, the 4G cellular operator does not allow accessing the frpc android client through an open port. So far, the only working way I have found is frp. In gost and xray chats, they said they don't know how to replace socks5 plugin or SocksServerUltimate.apk for my android phones.

If you know how my scheme can be implemented, I would like to discuss it, and of course discuss the amount of payment.

**Comment by heiher** [comment]
I suggest you run hev-socks5-tunnel or hev-socks5-tproxy on router of windows host.
