### ISSUE TITLE
使用密码认证会多一个rtt吗?

### ISSUE THREAD

**Issue by CCCAUCHY** [heiher/hev-socks5-server#39]

**Comment by heiher** [comment]
这取决于客户端怎么实现。为了减少延迟，hev-socks5-tunnel和hev-socks5-tproxy客户端使用的hev-socks5-core库实现是请求写合并发送的，因此不会多一个RTT。

**Comment by CCCAUCHY** [comment]
> 这取决于客户端怎么实现。为了减少延迟，hev-socks5-tunnel和hev-socks5-tproxy客户端使用的hev-socks5-core库实现是请求写合并发送的，因此不会多一个RTT。

为了减少RTT, 出站和入站也默认使用TFO吗? 被的代理流量是否也会使用TFO?

**Comment by heiher** [comment]
没有使用TFO。
