### ISSUE TITLE
Traffic monitoring

### ISSUE THREAD

**Issue by vavrecan** [heiher/hev-socks5-server#43]
Hello,

I'm wondering if it's possible to track traffic and associate it with a username. For UDP, it's relatively straightforward, as the transferred size is in res variable of hev_socks5_udp_fwd_f / hev_socks5_udp_fwd_b.

However, for TCP, it presents a more challenging modification due to the task system performing a copy, and it doesn't expose the size of transferred data. Do you have any ideas on how to achieve this for TCP?

Thank you!

**Comment by heiher** [comment]
Now we can mark upstream traffic for each user, so I think using `iptables` to count is a good way.

https://github.com/heiher/hev-socks5-server#authentication-file

**Comment by vavrecan** [comment]
There are some limitations when using iptables (nftables + dynamic property) to count data for both the user and destination. In examining the task system, the socks5 server utilizes task_io_splicer and retains wlen. However, it lacks a straightforward method for accessing it. Perhaps, task_io_splicer_init could incorporate a reference to the close/flush callback method for easier access?

**Comment by heiher** [comment]
> There are some limitations when using iptables (nftables + dynamic property) to count data for both the user and destination. In examining the task system, the socks5 server utilizes task_io_splicer and retains wlen. However, it lacks a straightforward method for accessing it. Perhaps, task_io_splicer_init could incorporate a reference to the close/flush callback method for easier access?

Okay. I think you can override the `splicer` method of `HevSocks5TCP`/`HevSocks5UDP` in the `HevSocks5Session`, to use a custom splice with counting.

https://github.com/heiher/hev-socks5-core/blob/664beaa4e7df3f10dbb28f0ec90dfadc9bc4de76/src/hev-socks5-tcp.h#L26

Here is an example:

https://github.com/heiher/hev-socks5-tunnel/blob/master/src/hev-socks5-session-tcp.c#L350

**Comment by vavrecan** [comment]
Does it make sense to implement tcp splitter from tunnel in tproxy?

**Comment by heiher** [comment]
@vavrecan tcp splitter?

**Comment by vavrecan** [comment]
Yes - is there any reason tunnel is not using same tcp splitter as tproxy?

**Comment by vavrecan** [comment]
I am thinking about changing hev_task_io_splice adding two new parameters, size_t *sent, size_t *received and then just incrementing new variable in _HevTaskIOSplicer structurure (as it is using IO_SPLICE_SYSCALL - its more performer isn't it?

**Comment by heiher** [comment]
> I am thinking about changing hev_task_io_splice adding two new parameters, size_t *sent, size_t *received and then just incrementing new variable in _HevTaskIOSplicer structurure (as it is using IO_SPLICE_SYSCALL - its more performer isn't it?

Yeah. You need a custom `splicer` with counting.

**Comment by heiher** [comment]
Here is an example: https://github.com/heiher/hev-socks5-server/commit/08be977439283616948662071f79944521fbba2a
