### ISSUE TITLE
[Feature] Android JNI shared library

### ISSUE THREAD

**Issue by heiher** [heiher/hev-socks5-server#47]
Add support for Android JNI shared library.

**Comment by andrin-n-dream** [comment]
Is there any update on this?
I would love to use the server with a recent Android Project targeting SDK 33. There is no way to run the executable from within the app. I would be very thankful if you could explain, how we could run the server from within a Java Android App >= SDK 33.

**Comment by heiher** [comment]
Fixed: https://github.com/heiher/hev-socks5-server/commit/2f12f5bf92fa7bc78b057666ecfa89cafe9c13b2
