### ISSUE TITLE
希望能支持以 daemon 的方式后台运行

### ISSUE THREAD

**Issue by pexcn** [heiher/hev-socks5-server#5]
就像 ss-server 的 [`-f` 参数](https://github.com/shadowsocks/shadowsocks-libev/blob/master/doc/ss-server.asciidoc)一样

```
-f <pid_file>
    Start shadowsocks as a daemon with specific pid file.
```

**Comment by heiher** [comment]
可以的，我通常是作为 systemd.service 运行的。

/etc/systemd/system/hev-socks5-server.service
```
[Unit]
Description=HevSocks5Server
After=network.target

[Service]
User=nobody
ExecStart=/usr/local/bin/hev-socks5-server /usr/local/etc/hev-socks5-server.conf
KillMode=process
Restart=always
LimitNOFILE=65536

[Install]
WantedBy=multi-user.target
```

**Comment by heiher** [comment]
Fixed.

https://github.com/heiher/hev-socks5-server/commit/cf186e8c41694fa77f53f7b53003f530bb2dbcd9

**Comment by pexcn** [comment]
感谢支持😄😄

**Comment by pexcn** [comment]
@heiher 还有个问题，能不能把命令行里面的指定 pid 的参数移动到 ini 配置文件里面？这样看起来会更优雅一点，另外希望添加一个能像 systemd.service 的 LimitNOFILE 设置 nofile 的参数。
整个配置文件看起来就像：

```ini
; Main configuration for hev-socks5-server

[Main]
Workers=4
Port=1080
ListenAddress=0.0.0.0
DNSAddress=8.8.8.8

;[Auth]
;Username=
;Password=

;[Misc]
;pid=/run/hev-socks5-server.pid
;nofile=65535
```

**Comment by heiher** [comment]
最初我是想加到配置文件中的，但又考虑会不会PID文件的路径是要启动时才确定并传递的。

如果能统一到配置文件是比较好的，再调整一下。

**Comment by heiher** [comment]
Fixed.

https://github.com/heiher/hev-socks5-server/commit/267011a2e7398e491e5bcd11e4a213043434ef0d

**Comment by pexcn** [comment]
感谢作者，已测试可以正常使用了。commit 很干净。
