### ISSUE TITLE
microsocks benchmark

### ISSUE THREAD

**Issue by rofl0r** [heiher/hev-socks5-server#51]
hi, i just updated microsocks (git master) to achieve higher throughput.
could you update your benchmark ? thanks!

**Comment by heiher** [comment]
Great! I'll remeasure it.

**Comment by heiher** [comment]
Congratulations!

## microsocks

Repo: https://github.com/rofl0r/microsocks

Version: git 98421a21

Command:

```bash
microsocks -q -i 0.0.0.0 -p 1080
```

### Upload

```
$ proxychains iperf3 -c 127.0.0.1
- - - - - - - - - - - - - - - - - - - - - - - - -
Speed:     32Gbps
CPU usage: 56%
MEM usage: 1.5M
```

```
$ proxychains iperf3 -c 127.0.0.1 -P 10
- - - - - - - - - - - - - - - - - - - - - - - - -
Speed:     191Gbps
CPU usage: 900%
MEM usage: 1.5M
```

### Download

```
$ proxychains iperf3 -c 127.0.0.1 -R
- - - - - - - - - - - - - - - - - - - - - - - - -
Speed:     32.1Gbps
CPU usage: 56%
MEM usage: 1.5M
```

```
$ proxychains iperf3 -c 127.0.0.1 -R -P 10
- - - - - - - - - - - - - - - - - - - - - - - - -
Speed:     185Gbps
CPU usage: 898%
MEM usage: 1.5M
```

**Comment by heiher** [comment]
I also need to remeasure the other socks5 servers because things changed on Linux 6.9.1. :joy:

**Comment by rofl0r** [comment]
hmm, those numbers look identical to what you have in the old graph

**Comment by heiher** [comment]
> hmm, those numbers look identical to what you have in the old graph

What you are looking at is the chart I have since updated. I have also updated the [comment](https://github.com/heiher/hev-socks5-server/issues/51#issuecomment-2130673603) above so that now you can see the before and after.

**Comment by rofl0r** [comment]
cool, thanks!
