### ISSUE TITLE
Alpine 下交叉编译的问题

### ISSUE THREAD

**Issue by rampageX** [heiher/hev-socks5-server#52]
Alpine 版本：
`Linux alpine 6.1.60-0-lts #1-Alpine SMP PREEMPT_DYNAMIC Wed, 25 Oct 2023 15:45:31 +0000 x86_64 Linux`

问题：
交叉编译命令：
`CROSS_PREFIX=arm-linux-musleabi- make ENABLE_STATIC=1`
发现编译出来的文件还是宿主机的架构 x86_64

加入调试：
`CROSS_PREFIX=arm-linux-musleabi- make ENABLE_STATIC=1 V=1`
发现编译的时候还是用宿主机的 gcc 和 cpp 等工具而不是交叉编译的工具

修改 Makefile 文件可以解决，包括主 Makefile 文件和 third-part 目录下的两个 Makefile 文件，屏蔽掉文件中的 `CROSS_PREFIX :=` 行：

`CROSS_PREFIX :=` ： ---->  `#CROSS_PREFIX :=` ：

则可以正确交叉编译出需要的平台文件。调试信息也可以看到正确的调用了交叉编译工具。

**Comment by heiher** [comment]
试试

```sh
make CROSS_PREFIX=arm-linux-musleabi- ENABLE_STATIC=1
```

**Comment by rampageX** [comment]
> 试试
> 
> ```shell
> make CROSS_PREFIX=arm-linux-musleabi- ENABLE_STATIC=1
> ```

这样可以了，神奇~
