### ISSUE TITLE
user connection limit

### ISSUE THREAD

**Issue by enakhi** [heiher/hev-socks5-server#54]
Could you please add a property to the auth.txt file to set the maximum number of connections allowed for each user? Additionally, can you ensure the server is handling this limitation properly?

**Comment by heiher** [comment]
You can limit the number of connections of user by firewall, matching the mark value in `auth.txt`.

**Comment by enakhi** [comment]
Could you please explain it using an example?

**Comment by heiher** [comment]
> Could you please explain it using an example?

For example, limit the number of connections for user `jerry` up to `2`.

config file:

```yaml
auth:
  file: conf/auth.txt
```

auth.txt:

```
jerry pass 1a
```

iptables:

```sh
iptables -A OUTPUT -p tcp --syn -m mark --mark 0x1a -m connlimit --connlimit-above 2 -j REJECT
```
