### ISSUE TITLE
Document about to use ipv6 

### ISSUE THREAD

**Issue by hongphu8790** [heiher/hev-socks5-server#56]
Hello,

I am looking for document about config to use ipv6.

Example i have interfaces:

- eth0 with ipv4: 192.168.1.5

- eth1 with ipv4: 192.168.25.100 / ipv6: 2001:ee0:262:xxx:xxx:9328:2244:c17d

Should i will define with config? 

Expect i want to use curl will access ipv6 network
```
curl ifconfig.io -x socks5://192.168.1.5:1080 -6
```
result:

```
2001:ee0:262:xxx:xxx:9328:2244:c17d
```

Thanks,

**Comment by heiher** [comment]
The socks5 server does not require any configs other than ensuring that the system has the correct IPv6 routing.

**Comment by hongphu8790** [comment]
> The socks5 server does not require any configs other than ensuring that the system has the correct IPv6 routing.

I tried curl with -6, it's not working, but -4 return IPv4 normally, seem hev is not support dualstack.
With 3proxy, have option -6 or -46, -64 for fallback.

**Comment by hongphu8790** [comment]
I tested again with config `domain-address-type: ipv6`, seem working with socks5h only, for socks5 still response ipv4, seem need config dns ipv6 locally to resolve in this case

**Comment by heiher** [comment]
`socks5h` resolves domain names on the server side, `socks5` does it locally. If the client side cannot resolve the AAAA record of the domain name (or is not preferred), this will affect IPv6, even if the server side supports IPv6 and the socks5 server is dual stack.
