### ISSUE TITLE
[Feature request] Ability to bind to both IPv4 and IPv6 address with option bind-address

### ISSUE THREAD

**Issue by przemyslaw0** [heiher/hev-socks5-server#60]
This SOCKS5 server can bind to only one IP. I would like to bind to both IPv4 and IPv6, for using IPv4 and 6 of my VPN connection.

Could you implement this?

**Comment by heiher** [comment]
Is it possible to do this with bounding network interface?

```yaml
main:
  bind-interface: 'eth0'
```

**Comment by heiher** [comment]
> I know this option, but it requires root (correct if I'm wrong).

No, it does not require root.

**Comment by heiher** [comment]
> Got, I don't know why it doesn't require administrator privileges, I asked that because SO_BINDTODEVICE requires root.

`SO_BINDTODEVICE` does not require root.
