### ISSUE TITLE
Mark traffic without users auth file

### ISSUE THREAD

**Issue by GektorUA** [heiher/hev-socks5-server#65]
I am using hev-socks5-server without authorization but many instances on different SOCKS5 ports, is there any way to mark whole traffic of each instance without user authorization?

**Comment by heiher** [comment]
It seems we still need an fwmark as the global default. Using uid-owner for matching in netfilter is a common approach. If the listening port is below 1024, I think you’ll need to add [`cap_net_bind_service`](https://man7.org/linux/man-pages/man7/capabilities.7.html).
