### ISSUE TITLE
用 shell 脚本执行静态编译无效？

### ISSUE THREAD

**Issue by pexcn** [heiher/hev-socks5-server#7]
socks5-server 的作者你好：

今天遇到了个问题，我尝试对这个程序进行静态编译，手动静态编译没有问题。但是当把命令写在脚本里面，静态编译似乎就变成了动态编译的了，具体代码在这几行（不知道是不是写错了？）：[build.sh#L143-L148](https://github.com/pexcn/static-build-ci/blob/c5a3469206224fc274f8a8a53e35dab3e2b7c7b4/build.sh#L143-L148)

用 travis-ci 编译出来的二进制在：[socks5-server-linux-x86_64-20190317.tar.gz](https://github.com/pexcn/static-build-ci/releases/download/20190317/socks5-server-linux-x86_64-20190317.tar.gz)

之后我把它下载到本地，文件显示 `dynamically linked`：

```bash
root@Debian:~# ldd socks5-server
        linux-vdso.so.1 (0x00007ffdc2fdc000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f2e6fb03000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f2e6f758000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f2e6fd28000)

root@Debian:~# file socks5-server
socks5-server: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=41b983e3130eea59fc36d5ec5010a7345221b9be, stripped
```

**Comment by pexcn** [comment]
我刚刚发现在 make install 之后，它会从静态链接变成动态链接

**Comment by heiher** [comment]
是的，需要在make install上一并增加ENABLE_STATIC=1

**Comment by pexcn** [comment]
好的，如果我在 make 的时候指定了 CROSS_PREFIX, 那么在 make install 的时候也要同时指定 CROSS_PREFIX 吗？

**Comment by heiher** [comment]
对的。

**Comment by pexcn** [comment]
好的，谢谢。
