### ISSUE TITLE
为什么能同时运行两个进程来监听同一端口？

### ISSUE THREAD

**Issue by pexcn** [heiher/hev-socks5-server#8]
我的配置文件 `/etc/socks5-server.conf`：

```ini
[Main]
Workers=4
Port=***
ListenAddress=0.0.0.0
DNSAddress=8.8.8.8

[Auth]
Username=*****
Password=**********

[Misc]
PidFile=/run/socks5-server.pid
LimitNOFile=65535
```

执行两次启动命令：
```bash
socks5-server /etc/socks5-server.conf
socks5-server /etc/socks5-server.conf
```

然后 `ps aux`, 发现存在两个 socks5-server 的进程，难道不应该在执行第二个启动命令的时候报错吗？

**Comment by heiher** [comment]
哈哈，这是因为启用了socket reuseport来支持多线程listen，对多进程也有效的。

**Comment by pexcn** [comment]
看来是这个：https://lwn.net/Articles/542629/
如果在第二个进程启动时，能显示个警告就好了，开启 port reuse 会有性能提升吗？

另外看到了最近的双栈支持了，要是可以添加一个 `IPv6First` 选项就好了，优先使用 IPv6 :laughing:

**Comment by pexcn** [comment]
抱歉，我好像有点说得不太清楚，`IPv6First` 意思是和 https://github.com/shadowsocks/shadowsocks-libev/blob/master/doc/ss-server.asciidoc 的 `-6` 的功能是一样的。:grinning:

**Comment by heiher** [comment]
> 看来是这个：https://lwn.net/Articles/542629/
> 如果在第二个进程启动时，能显示个警告就好了，开启 port reuse 会有性能提升吗？

最初多Worker（线程）是Listen同一个socket fd的，存在epoll惊群问题，后来改成port reuse来规避。

> 
> 另外看到了最近的双栈支持了，要是可以添加一个 `IPv6First` 选项就好了，优先使用 IPv6 laughing

嗯，在支持双栈时是考虑目前V4支持更好，所以按V4优先实现的，加个V6优先的参数的确是个很好的补充。

**Comment by heiher** [comment]
> 抱歉，我好像有点说得不太清楚，`IPv6First` 意思是和 https://github.com/shadowsocks/shadowsocks-libev/blob/master/doc/ss-server.asciidoc 的 `-6` 的功能是一样的。grinning

[v1.8.2](https://github.com/heiher/hev-socks5-server/releases/tag/1.8.2)

**Comment by pexcn** [comment]
非常感谢，明天尝试下 :)
